### ISSUE TITLE
Scss compiler error: File to import: {wolves:bourbon}/bourbon not found

### ISSUE THREAD

**Issue by jbelmont** [wolvesio/meteor-bourbon#11]
Hello:

I am getting the following error when using Webstorm 10 with wolves:bourbon package:
While processing files with fourseven:scss (for target web.browser):
   /client/recipes/styles/navbar.scss: Scss compiler error: File to import: {wolves:bourbon}/bourbon not found. Import origin:
   /client/recipes/styles/navbar.scss

It cannot seem to resolve the bourbon file

**Comment by wolves** [comment]
Are you using Version 1.2.0 or higher of Meteor

**Comment by rista404** [comment]
I got a similar error:

```sh
While building the application:
   /Users/user/Projects/project/client/stylesheets/style.sass:1:9: Scss compiler error: file to import not found or
   unreadable: {wolves:bourbon}/bourbon
   Current dir: /Users/user/Projects/project/client/stylesheets/
```

Any ideas?
Cheers!

**Comment by wolves** [comment]
Please include the version of Meteor you are using when you receive this error

**Comment by rista404** [comment]
`METEOR@1.2.1`

**Comment by JobV** [comment]
Experiencing the same issue, but with my scss file.
Also meteor `1.2.1`.

```
 While processing files with fourseven:scss (for target web.browser):
   /testly.scss: Scss compiler error: File to import: {}/wolves:bourbon/bourbon
   not found in file: /job/abc/{}/abc.scss
```

**Comment by stephan281094** [comment]
I ran into the same problem, but I fixed it by doing the following:
* `meteor remove wolves:bourbon fourseven:scss`
* `meteor add fourseven:scss`
* `meteor add wolves:bourbon`

It seems important that fourseven:scss gets added first.

**Comment by wolves** [comment]
Yes it is. Thank you for sharing that. Marking closed.

**Comment by dmitry-sher** [comment]
Looks like broken again with Meteor 1.5

**Comment by k2project** [comment]
still not working.

**Comment by wolves** [comment]
When Meteor switched to using npm I figured this package wasn't necessary any longer considering you are able to use bourbons default npm package.

Instructions can be found here: https://github.com/thoughtbot/bourbon#installing-with-npm-and-using-a-node-based-asset-pipeline

Updating readme with this information

**Comment by k2project** [comment]
HI Christopher,

Thank you so much for getting back to me on that issue.

Cheers,
Kris
