### ISSUE TITLE
Package doesn't work with Meteor 1.0.2

### ISSUE THREAD

**Issue by acemtp** [wolvesio/meteor-bourbon#3]
I just install it, `.meteor/local/build/programs/server/assets/packages/wolves_bourbon` exists but only contains on file `_bourbon.scss`. I wonder if it's related to new Meteor optimization.

**Comment by aleatorik** [comment]
I am currently using it in a 1.0.2 project and getting it to work, but will look into this

**Comment by aleatorik** [comment]
This may also be resolved with a pending PR (https://github.com/wolvesio/meteor-bourbon/pull/2) that I hope to get in shortly

**Comment by aleatorik** [comment]
This should now be fixed with this order update - https://github.com/wolvesio/meteor-bourbon/commit/ac31f3767562d427a20f87b623dabeac16ac8520
