### ISSUE TITLE
Text selection mixin

### ISSUE THREAD

**Issue by stephan281094** [wolvesio/meteor-bourbon#5]
Hi there,

I tried including the `selection` mixin as it's documented on [bourbon.io/docs](http://bourbon.io/docs/#selection).
That gave me the following error:
```
Scss compiler error: no mixin named selection
```

I came to this repository and noticed that this mixin simply does not exist. It does, however, exist in the [origin repo](https://github.com/thoughtbot/bourbon/blob/master/app/assets/stylesheets/css3/_selection.scss). I'm guessing that this repository is simply using an older version of Bourbon. Maybe it's time for an update?

**Comment by aleatorik** [comment]
Sure I will attempt to update this shortly. Keep in mind also that it is dependent on libsass rather than the main Boubon repo which has a release further forward based on its use in Rails

**Comment by aleatorik** [comment]
Updated to most recent Bourbon. Including "selection". Cheers mate
