### ISSUE TITLE
Cannot use with continuous integration

### ISSUE THREAD

**Issue by sungwoncho** [wolvesio/meteor-bourbon#6]
I would like to test my app with Travis-CI, but the test errors out on the CI server because `bourbon.scss` does not exist the first time the app is run.

Here is the error message:
```
While building the application:
   start_test.js:1:15: Unexpected token ILLEGAL
   /home/travis/build/path_to_stylesheet:
   Scss compiler error: file to import not found or unreadable: bourbon/bourbon
```

I understand from the README that I have to manually restart the app the first time around:
> the first time you run the app after installing the package your app will complain that it is unable to find it. For the moment this can be resolved by either stopping and restarting the app...

But it is hard to do because I am not in local. Is there a workaround to work with CI? Or any plans for removing the need for restart?

**Comment by aleatorik** [comment]
Unfortunately as of now I do not know of a solution for this issue. It has to do with how meteor handles package compilation and that it takes the first time to deposit the assets before they can be accessed upon starting the app
